import flet as ft

# --- Color Palette ---
COLOR_PRIMARY = ft.Colors.DEEP_PURPLE
COLOR_TEXT_DARK = ft.Colors.DEEP_PURPLE_900
COLOR_TEXT_ON = ft.Colors.WHITE
COLOR_BACKGROUND_WHITE = ft.Colors.WHITE
COLOR_TEXT_ON_WHITE = COLOR_TEXT_DARK
COLOR_BORDER = COLOR_TEXT_DARK
COLOR_DIVIDER_ON_WHITE = ft.Colors.GREY_300
COLOR_DIVIDER_ON_PURPLE = ft.Colors.with_opacity(0.5, ft.Colors.WHITE)
COLOR_INPUT_FIELD_BG_FILLED = ft.Colors.with_opacity(0.05, COLOR_PRIMARY)
COLOR_ICON_ON_WHITE = COLOR_TEXT_DARK
COLOR_ICON_ON_PURPLE = ft.Colors.WHITE
COLOR_BUTTON_TEXT = ft.Colors.WHITE 
COLOR_STATUS_TEXT_MUTED = ft.Colors.GREY_600